#!/usr/bin/env bash
#clock: display hours and minutes

hour=0
minute=1

while [[ $hour -le 12 ]]; do
	echo "Hour: $hour"
	minute=1
	while [[ $minute -le 59 && $hour -lt 12 ]]; do
		echo $minute
		minute=$((minute + 1))
	done
	hour=$((hour + 1))
done
