#!/usr/bin/env bash
#print-content: print the current directory content

for file in *; do
	if [[ $file == . ]]; then
		continue
	fi
	filename=$(echo "$file" | cut -d '-' -f2-)
	echo "$filename"
done
