#!/usr/bin/env bash
#validate a file

file="school"

if [[ -e $file ]]; then
	echo "school file exists"
	if [[ -s $file ]]; then
		echo "$file is not empty"
	else
		echo "$file file is empty"
	fi
	if [[ -f $file ]]; then
		echo "$file is a regular file"
	else
		continue
	fi

else
	echo "$file does not exist"
	exit 1
fi
